### ISSUE TITLE
I would like to know what files you have changed from the source code because I want to port admittance control to a new robotic arm

### ISSUE THREAD

**Issue by zbj165** [YuHoChau/UR16e_Admittance#1]
I would like to know what files you have changed from the source code because I want to port admittance control to a new robotic arm。
How can I understand the operating principle of this project。
我想知道你从源代码改了什么文件，因为我想把导纳控制移植到一个新的机械臂上

**Comment by YuHoChau** [comment]
你好，本repo只是基于[原作者](https://github.com/MingshanHe/Compliant-Control-and-Application)的基础上针对我的任务完成了细微改动，例如增加urdf增加base和end-effector; 参照了这篇[paper](https://ieeexplore.ieee.org/abstract/document/6224586?casa_token=UXYykAj1s1UAAAAA:UmCwdBJeMlr4oyVzg8NEwIzQ8v_wRFaz-J3epnr6S_Pt9o8xgZpAPv6-v1uMwyDLnO-0Hvw_UiI)增加了一个简单的variable admittance control的功能，本repo依然使用UR机械臂。

如果要移植到其他机械臂，请使用对应的ROS Driver并确保其提供相应的接口。同时由于UR e-series末端自带F/T sensor，能够通过`/wrench`直接读取力/力矩，如使用external F/T sensor请检查通讯及话题名称。更多细节可以参考[ros_contrl](http://wiki.ros.org/ros_control).

最后本repo将在之后进行代码重整，目前仅供参考。Hope this helps.

**Comment by zbj165** [comment]
> 你好，本repo只是基于[原作者](https://github.com/MingshanHe/Compliant-Control-and-Application)的基础上针对我的任务完成了细微改动，例如增加urdf增加base和end-effector;参照了这篇[论文](https://ieeexplore.ieee.org/abstract/document/6224586?casa_token=UXYykAj1s1UAAAAA:UmCwdBJeMlr4oyVzg8NEwIzQ8v_wRFaz-J3epnr6S_Pt9o8xgZpAPv6-v1uMwyDLnO-0Hvw_UiI)增加了一个简单的可变导纳控制的功能，本repo依然使用UR机械臂。
> 
> 如果要移植到其他机械臂，请使用对应的ROS Driver并确保其提供相应的接口。同时由于UR e-series末端自带F/T sensor，能够通过直接读取力/力矩，如使用外部F/T sensor请检查通讯及话题名称。更多细节可以参考[ros_contrl](http://wiki.ros.org/ros_control).`/wrench`
> 
> 最后本repo将在之后进行代码重整，目前仅供参考。希望这有帮助。

您好，十分感谢您的回答
