### ISSUE TITLE
Real UR5e robotic arm

### ISSUE THREAD

**Issue by zbj165** [YuHoChau/UR16e_Admittance#2]
How to use admittance control on a real robotic arm

**Comment by YuHoChau** [comment]
After confirming the effectiveness of the admittance algorithm in simulation like Gazebo, you may deploy it on a real robotic arm. I assum that you have already completed the configurations of the robot like URCaps external control and IP settings. Then it would be straightforward to:
1. run external control on the UR robot panel. 
2. bringup your robot through `ur_robot_driver` (please check [Universal_Robots_ROS_Driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/master)). e.g., `roslaunch ur_robot_driver ur5e_bringup.launch`
3. run admittance: `roslaunch Admittance Admittance.launch`.

For safety reasons, please lower the velocity on your UR robot panel before launching the admittance.

**Comment by zbj165** [comment]
In the second step, does this not require adding a controller

**Comment by YuHoChau** [comment]
You may find the answer in the official repo of UR ROS driver: https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/master.
